# Generated by Django 5.0.1 on 2024-02-03 13:14

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='featuredpost',
            managers=[
                ('live', django.db.models.manager.Manager()),
            ],
        ),
    ]
