# Generated by Django 5.0.1 on 2024-02-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_siteidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteidentity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
