# Generated by Django 5.0.1 on 2024-02-03 13:14

import blog.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_siteidentity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='layout',
            field=wagtail.fields.StreamField([('featured_posts', blog.blocks.FeaturedPostsBlock()), ('latest_posts', blog.blocks.LatestPostsBlock())], blank=True, use_json_field=True),
        ),
    ]
