# Generated by Django 5.0.1 on 2024-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_homepage_intro_homepage_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteidentity",
            name="tag_line",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
