# Generated by Django 5.0.3 on 2024-03-16 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatableGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('complexity', models.CharField(choices=[('R', 'Rabbit'), ('E', 'Elephant'), ('D', 'Deadline')], default='E', max_length=1)),
                ('frequency', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyGoalCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='weekly_stars.repeatablegoal')),
            ],
            options={
                'unique_together': {('goal', 'date')},
            },
        ),
    ]
